[project]
name = "notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "notebook>=7.5.6",
    "numpy>=1.23,<1.27",
    "numba>=0.57,<0.60",
    "python-dotenv>=1.2.2",
    "qwen-tts==0.0.5",
    "requests>=2.33.0",
    "llvmlite>=0.40,<0.43",
    "soundfile>=0.12.1",
    "torch>=2.2.0",
    "sounddevice>=0.4.7",
    "websocket-client>=1.8.0",
    "google-genai>=1.61.0",
]
